// Generated by Haxe 4.3.6
(function ($global) { "use strict";
var Main = function() { };
Main.main = function() {
	var point_x = 0;
	var point_y = 10;
	point_x += 10;
	console.log("Main.hx:5:",point_x);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.main();
})({});
